# Generated by Django 3.2.22 on 2023-11-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_owner'),
        ('posts', '0002_auto_20231102_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='categories.category'),
        ),
    ]
