# Generated by Django 3.2.22 on 2023-11-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20231113_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at']},
        ),
    ]
